// supastarter-nuxt-main/supastarter-nuxt-main/apps/web/modules/shared/components/TeamAvatar.vue
<script setup lang="ts">
  import { config } from "@config";
  import BoringAvatar from "vue-boring-avatars";

  const props = defineProps<{
    name: string;
    avatarUrl?: string | null;
  }>();
</script>

<template>
  <Avatar>
    <AvatarImage v-if="props.avatarUrl" :src="props.avatarUrl" />
    <AvatarFallback class="bg-primary/10 text-primary">
      <BoringAvatar
        :size="96"
        variant="marble"
        :name="name"
        :colors="config.teams.avatarColors"
      />
    </AvatarFallback>
  </Avatar>
</template>

// supastarter-nextjs-refactor-pricing/supastarter-nextjs-refactor-pricing/apps/web/modules/shared/components/TeamAvatar.tsx
import { Avatar, AvatarFallback, AvatarImage } from "@ui/components/avatar";
import BoringAvatar from "boring-avatars";
import { forwardRef, useMemo } from "react";

export const TeamAvatar = forwardRef<
  HTMLSpanElement,
  {
    name: string;
    avatarUrl?: string | null;
    className?: string;
  }
>(({ name, avatarUrl, className }, ref) => {
  const avatarSrc = useMemo(() => avatarUrl ?? undefined, [avatarUrl]);

  return (
    <Avatar ref={ref} className={className}>
      <AvatarImage src={avatarSrc} />
      <AvatarFallback>
        <BoringAvatar
          size={96}
          name={name}
          variant="marble"
          colors={["#4e6df5", "#e5a158", "#9dbee5", "#ced3d9"]}
        />
      </AvatarFallback>
    </Avatar>
  );
});

TeamAvatar.displayName = "TeamAvatar";
